### PR TITLE
introduce optional cli argument 2 alternative values to fill with

### PR DESCRIPTION
**Pull request by dallanto**
@takluyver  @tmichela 
A very crude and simple way to implement the requested feature of having missing modules filled with 0 instead of ``np.nan`` in the virtual CXI.

### CODE REVIEW

**Comment by tmichela** [comment]
@dallanto I outran you :D https://github.com/European-XFEL/EXtra-data/pull/59

We should have better coordinated that task

**Comment by dallanto** [comment]
It's probably wiser to fill the ``image.mask`` dataset with ones instead of zeroes. Thus we indicate there is something unusual (0 would indicate normal pixels, if I am not mistaken). If e.g. CrystFEL would thus ignore the missing, formally filled, module that's fine. If not - then it reads 0 for the ``image.data`` value, which is still better than NaN. What do you think?

**Comment by dallanto** [comment]
> @dallanto I outran you :D #59
> 
> We should have better coordinated that task

Yes, my bad. Congrats for outrunning me  : )

**Comment by dallanto** [comment]
Ok both, @takluyver, @tmichela  - I formally withdraw my pull request.  
Note that I commented on the issue and asked a question on you pull request, Thomas M.

**Comment by takluyver** [comment]
We went for #59 instead of this one.

**Pull request closed without merging**
