### PR TITLE
Speed up _check_source_conflicts()

### PR DESCRIPTION
**Pull request by takluyver**
Opening proposal 2926, run 74, with around 21000 files, was taking a very long time (long enough that I didn't wait for it to finish; the [report on Redmine](https://in.xfel.eu/redmine/issues/96112) mentions hours).

Using the poor man's sampling profiler (hitting Ctrl-C and looking at the traceback) I found that `_check_source_conflicts` was the culprit. This checks whether any source has the same train ID in different files. It was going through every source, and building up a set of train IDs seen so far, comparing each new file to that. This got slow with large numbers of files. This PR makes two changes:

- Rather than checking each new file and adding it to an array of train IDs, make one big array with train IDs from all files, and check it for duplicates. This avoids doing repeated numpy operations and reallocating an array.
- As one set of files typically contains several sources, cache the result on a frozenset of file paths, and reuse it for the next source related to the same set of files.

With this branch, I can open the run in 10-15 seconds.

```shell
time lsxfel /gpfs/exfel/exp/SQS/202121/p002926/raw/r0074
```

```python
%%time
extra_data.open_run(2926, 74)
```

### CODE REVIEW

**Comment by takluyver** [comment]
The test failures are related to the handling of bad train IDs. One of the sample files we make to test with has a duplicated train ID. Previously, `_check_source_conflicts` would only spot repeated train IDs *between* files, not *within* them. The new implementation complains about repeated train IDs in the same file.

We could recreate the previous behaviour exactly, but I'm inclined to say that a duplicate train ID inside a file is problematic enough (and hopefully rare enough) that it should fail the check. You would still be able to open it by passing `inc_suspect_trains=False`, so long as one of them is flagged as invalid.

**Comment by takluyver** [comment]
For now, I've updated the tests to match the new behaviour (failing on duplicated train IDs unless `inc_suspect_trains=False`). We can knock that commit off if we choose to go the other way.

**Review by tmichela — APPROVED** [review]
> We could recreate the previous behaviour exactly, but I'm inclined to say that a duplicate train ID inside a file is problematic enough (and hopefully rare enough) that it should fail the check. You would still be able to open it by passing inc_suspect_trains=False, so long as one of them is flagged as invalid.

Let's hope we don't end up with the same kind of issue #178 fixed :upside_down_face: 
But I don't recall ever seeing this, so... :crossed_fingers: LGTM

**Comment by tmichela** [comment]
Just for the sake of it, I checked an few 100 runs  I know with trainId issues, and did not any duplicate Train ID in the same file

**Comment by takluyver** [comment]
Thank-you! :grinning: :+1:

**Pull request merged**
