### PR TITLE
Method to get RUN values

### LINKED ISSUE #26: Provide a means to access RUN data
RUN stores a single value from each control data field, for the start of the run. This is duplicated in all the sequence files, but it still contains the data from the start of the *run*, not the start of that file, if I've understood correctly.

Previously we ignored this, because all the same data was in CONTROL anyway. Now it's possible to mark fields as omitted, in which case they won't be stored under CONTROL, but they will still have a snapshot in RUN.

This is low priority for now, because I imagine that the data people are interested in will still be recorded in CONTROL. It can be re-prioritised if we hear about a use case that needs it.

### PR DESCRIPTION
**Pull request by takluyver**
Closes #26

To keep things fast & simple, this just selects an arbitrary file for the relevant source to get the RUN data from. Within a run, the value should be the same in all files.

If you combine runs with `.union()`, you'll get the value from an arbitrary one of the runs. If that was likely to come up often, I'd want to load the value from each run and error if they're inconsistent. But I think merging runs is relatively unusual, and checking for it has a cost in either performance or complexity, so for now I'm ignoring it.

```
In [2]: run = open_run(2702, 173)                                               

In [3]: run.get_run_value('HED_OPT_PAM/CAM/SAMPLE_CAM_4', 'triggerMode')        
Out[3]: 'ExtTrigMult'

In [4]: run.get_run_value('HED_OPT_PAM/CAM/SAMPLE_CAM_4', 'triggerMode.value')  
Out[4]: 'ExtTrigMult'
```

### CODE REVIEW

**Comment by takluyver** [comment]
Regarding combining runs: we're going to face the same question for reading metadata fields like run number & start time (#27), and I'm less convinced that 'arbitrary one' is the right answer there. So we might decide we need some mechanism for tracking groups of files associated with the same run anyway.

**Comment by philsmt** [comment]
How unfortunate we missed the 1.5 milestone for this one, as it happens I've got a use case for this coming up soon 😞 

> Regarding combining runs: we're going to face the same question for reading metadata fields like run number & start time (#27), and I'm less convinced that 'arbitrary one' is the right answer there. So we might decide we need some mechanism for tracking groups of files associated with the same run anyway.

Depending on the experiment, combining runs is actually fairly common, e.g. for lots of AMO-related experiments. Here you often need to collect statistics, but spread the same configuration across several runs if some parameter tends to be unstable.

I'd propose rather than introducing a new layer into EXtra-data to track the run a `DataCollection` belongs to and resolve conflicts, we could simply refuse providing a RUN value whenever it's not clear (based on a cheap check) all files belong to a particular run. Hence, when a user is combining runs, they have to sort out the conflict explicitly on their side.

**Comment by takluyver** [comment]
I like that idea, at least as a starting point - we can do something smarter later if people need it. For the first cut, I'll assume that any DataCollection that comes from `.union()` may be multiple runs.

Releases aren't hard to make, so if you want this soon, we can make 1.6 after merging the PR.

**Comment by philsmt** [comment]
Playing around with having keys only in `RUN` and not `CONTROL`, we might want to extend `lsxfel`? It currently lists only what can be found in `CONTROL`.

**Comment by philsmt** [comment]
The ultimate solution should probably to list the keys found in either, and have access transparently choose the clostest `CONTROL` value to a given train and `RUN` if there's none in EXtra-data proper. But that's an entirely different beast.

For the interim, given `lsxfel` already has this header for `CONTROL` data
> N control sources: (1 entry per train)

It might make the most sense to add a section for `RUN` data (if present):

> M control sources: (1 entry per run)

Or more simple and to integrate the section name:

> M run sources:

**Comment by takluyver** [comment]
How about this:

```
23 control sources: (1 entry per train)
  - HED_EXP_FDI/CAM/CAM_3
  - HED_IA1_TSC-1/CAM/TARGET_FRONT
  - HED_IA1_TSC-1/PROC/TARGET_FRONT
  - HED_IA1_TSC-2/CAM/TARGET_BACK
  - HED_IA1_TSC-2/PROC/TARGET_BACK
  - HED_OPT_IPM/ADC/1
  - HED_OPT_PAM/CAM/SAMPLE_CAM_4
    - Logger.file.maxBackupIndex.timestamp	[uint64]
    - Logger.file.maxBackupIndex.value	[uint32]
    - Logger.file.maxFileSize.timestamp	[uint64]
    ...
    - temperature.timestamp	[uint64]
    - temperature.value	[float64]
    + extra RUN keys (1 entry per run):
      - Logger.file.category.timestamp	[uint64]
      - Logger.file.category.value	[string]
      - Logger.file.filename.timestamp	[uint64]
      - Logger.file.filename.value	[string]
      - Logger.file.pattern.timestamp	[uint64]
      ...
```

**Comment by philsmt** [comment]
Works great on the files I've created, thanks!

I'd probably not sort `RUN` below `CONTROL` (in particular given your example regarding DaqPolicy), but that's an aesthetic issue.

**Comment by takluyver** [comment]
Would you put RUN above? Or mix the groups so they're in one alphabetic sequence? I'm guessing that RUN data are generally less important (given that we've got this far without exposing them).

**Comment by philsmt** [comment]
I would probably put them on the same level (with either one first). We could remove the "1 entry per train" without `--detail` and just list sources, and show either section (if necessary) with `--detail`.
In reality, plenty of `CONTROL` data is actually `RUN` data, but nobody bothered to update the DaqPolicy.

**Comment by takluyver** [comment]
I'm not quite following your description. You mean a separate section listing run sources like for control sources? I'm grouping them like this because there aren't (as far as I know) separate sources for run - the data in the RUN section is extra information attached to control sources. But I still want to make the distinction clear, because it affects how you can access and use them.

**Comment by philsmt** [comment]
I understand, and either view of this is probably valid. I'll give my point another attempt:

Starting from Karabo, properties have either `DaqPolicy.OMIT` (only found in `RUN`) or `DaqPolicy.SAVE` (found in `RUN` once and `CONTROL` per train). Both is control data with the only distinction of meant to change over a run or not. So if looking at details, there is just the device with control data (i.e. is present in `CONTROL` and/or `RUN`, probably and). If looking with details, there are two sections with train-constant data and run-constant data (depending on which has any key).

Unfortunately, a property missing this is assigned `DaqPolicy.UNSPECIFIED`, which is equivalent to `DaqPolicy.SAVE`. And over the last year, little has changed on that front. Thus, it looks like most data is train-constant, even though it's run-constant.

**Comment by takluyver** [comment]
That's how I see it too, but at the level of sources (aka Karabo devices), there is only one list of control sources - the RUN section may have extra properties within a source, but it doesn't have extra sources. So I'd like to display just one list of control sources, and split out the different keys under a given source when showing the details.

Is putting `(1 entry per train)` at the top of the section the sticking point? What about something like this?

```
23 control sources:
  - HED_EXP_FDI/CAM/CAM_3
  - HED_IA1_TSC-1/CAM/TARGET_FRONT
  - HED_IA1_TSC-1/PROC/TARGET_FRONT
  - HED_IA1_TSC-2/CAM/TARGET_BACK
  - HED_IA1_TSC-2/PROC/TARGET_BACK
  - HED_OPT_IPM/ADC/1
  - HED_OPT_PAM/CAM/SAMPLE_CAM_4
    - Control keys (1 entry per train):
      - Logger.file.maxBackupIndex.timestamp	[uint64]
      - Logger.file.maxBackupIndex.value	[uint32]
      - Logger.file.maxFileSize.timestamp	[uint64]
      ...
      - temperature.timestamp	[uint64]
      - temperature.value	[float64]
    - Extra run keys (1 entry per run):
      - Logger.file.category.timestamp	[uint64]
      - Logger.file.category.value	[string]
      - Logger.file.filename.timestamp	[uint64]
      - Logger.file.filename.value	[string]
      - Logger.file.pattern.timestamp	[uint64]
      ...
```

**Comment by philsmt** [comment]
I tihnk that's what I meant all along, and in my head the `(1 entry per train)` applied to properties, not full sources. I probably confused myself by only looking at files with a single one. Thanks!

Love your idea!

While you're at it, the current implementation does not sort the `RUN` keys 😄

**Comment by takluyver** [comment]
OK, I've implemented something similar to that:

```
23 control sources:
  - HED_EXP_FDI/CAM/CAM_3
  - HED_IA1_TSC-1/CAM/TARGET_FRONT
  - HED_IA1_TSC-1/PROC/TARGET_FRONT
  - HED_IA1_TSC-2/CAM/TARGET_BACK
  - HED_IA1_TSC-2/PROC/TARGET_BACK
  - HED_OPT_IPM/ADC/1
  - HED_OPT_PAM/CAM/SAMPLE_CAM_4
    - Control keys (1 entry per train):
      - Logger.file.maxBackupIndex.timestamp	[uint64]
      - Logger.file.maxBackupIndex.value	[uint32]
      - Logger.file.maxFileSize.timestamp	[uint64]
      - Logger.file.maxFileSize.value	[uint32]
      ...
      - temperature.timestamp	[uint64]
      - temperature.value	[float64]
    - Additional run keys (1 entry per run):
      - Logger.file.category.timestamp	[uint64]
      - Logger.file.category.value	[string]
      - Logger.file.filename.timestamp	[uint64]
      - Logger.file.filename.value	[string]
      - Logger.file.pattern.timestamp	[uint64]
      - Logger.file.pattern.value	[string]
      ...
```

I also wonder about hiding the `.timestamp` entries and adding a note at the bottom like 'Each key also has .timestamp (uint64)', to make the list more compact. But that is a separate question from this PR. It also depends a bit whether we want to preserve the idea that every key has an associated timestamp or not.

**Comment by philsmt** [comment]
Thanks, seems to work nicely.

There's one issue I have, but I may break the EuXFEL file spec here myself. Naively, I've created most of my datasets with `create_dataset(key, data=value)`, which causes scalar datasets for, well, scalar values. This PR then throws:

```python
ValueError                                Traceback (most recent call last)
<ipython-input-7-ee1ffd82e7ba> in <module>
----> 1 run.get_run_value('SQS_REMI_DLD6/DET/BOTTOM', 'trigger.method')

~/code/EXtra-data/extra_data/reader.py in get_run_value(self, source, key)
    618             raise PropertyNameError(key, source)
    619
--> 620         val = ds[0]
    621         if isinstance(val, bytes):  # bytes -> str
    622             return val.decode('utf-8', 'surrogateescape')

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/gpfs/exfel/sw/software/xfel_anaconda3/1.1/lib/python3.7/site-packages/h5py/_hl/dataset.py in __getitem__(self, args, new_dtype)
    764         if self.shape == ():
    765             fspace = self.id.get_space()
--> 766             selection = sel2.select_read(fspace, args)
    767             if selection.mshape is None:
    768                 arr = numpy.ndarray((), dtype=new_dtype)

/gpfs/exfel/sw/software/xfel_anaconda3/1.1/lib/python3.7/site-packages/h5py/_hl/selections2.py in select_read(fspace, args)
     99     """
    100     if fspace.shape == ():
--> 101         return ScalarReadSelection(fspace, args)
    102
    103     raise NotImplementedError()

/gpfs/exfel/sw/software/xfel_anaconda3/1.1/lib/python3.7/site-packages/h5py/_hl/selections2.py in __init__(self, fspace, args)
     84             self.mshape = ()
     85         else:
---> 86             raise ValueError("Illegal slicing argument for scalar dataspace")
     87
     88         self.mspace = h5s.create(h5s.SCALAR)

ValueError: Illegal slicing argument for scalar dataspace
```

Now I've seen the DAQ to use 1-len arrays instead of scalars, is this our assumption for any EuXFEL data?

**Comment by takluyver** [comment]
We are currently assuming that RUN contains 1D, length 1 datasets rather than scalars. I'd agree that scalars make more sense in principle, and it wouldn't be too difficult to support them if we needed to, but I think I'd encourage you to match what the DAQ writes in this case. Consistency is nice. :slightly_smiling_face:

**Comment by philsmt** [comment]
Ah, but there is CONTROL data with length > 1, e.g. `VECTOR_STRING` properties. It does not happen too often, but there are a few devices out there with it. It is true however that currently (might change in Karabo 2.11), a bound device cannot have `NDARRAY_ELEMENT` properties, i.e. multidimensional data.

So it is true we do not need to support scalar datasets, but CONTROL data may have any length.

**Comment by takluyver** [comment]
Do you know where I might find some such data to check what shape it is? I would guess that both RUN and CONTROL become 2D, with the first dimension in RUN still being length 1.

**Comment by takluyver** [comment]
Found one that fits with my expectation, but I'm interested if you have examples with strings.

```
% h5glance /gpfs/exfel/exp/SPB/202130/p900188/raw/r0455/RAW-R0455-AGIPD1MCTRL01-S00000.h5 RUN/SPB_DET_AGIPD1M-1/CC/MON_0/veto_pattern/
/gpfs/exfel/exp/SPB/202130/p900188/raw/r0455/RAW-R0455-AGIPD1MCTRL01-S00000.h5/RUN/SPB_DET_AGIPD1M-1/CC/MON_0/veto_pattern/
├timestamp	[uint64: 1]
└value	[uint32: 1 × 1000]
```

**Comment by philsmt** [comment]
Ah, but I see the problem... here's an example file I found

```
RAW-R0077-DA03-S00000.h5/RUN (3 attributes)
├SQS_AQS_LAS
│ └SPEC
│   └800
│     ├acqRate
│     │ ├timestamp   [uint64: 1]
│     │ └value       [float64: 1]
│     ├bkgSpectrum
│     │ ├timestamp   [uint64: 1]
│     │ └value       [uint16: 1 × 2068]
```

So that's also on me. `VECTOR` data must have two axes 😞

**Comment by takluyver** [comment]
I'm working on the assumption that `run_dset.shape == ctrl_dset[:1].shape`.

**Comment by philsmt** [comment]
Works like a charm for both regular raw data with both `CONTROL` and `RUN`, as well as the new files with plenty of `RUN` values without `CONTROL`. Happy with the API, will save a lot of typing if you want just this one control value you doesn't change.

When going over a novice workflow for the upcoming users, I've realized however that opening a run with both `raw` and `proc` is somewhat awkward. I've come up with #174 to address this. Happy to merge this first and base #174 on master, or merge here first.

LGTM the rest!

**Comment by takluyver** [comment]
I'd prefer to land this one and retarget #174 to master, as it sounds like you're happy with that as well. There's another branch I'm waiting to make a PR from once this lands. :slightly_smiling_face:

**Pull request merged**
