### PR TITLE
Add support to open run data from any number of data locations

### PR DESCRIPTION
**Pull request by philsmt**
Somewhat coincidental to our internal discussion on differentiating data from `raw` and `proc`, I already planned to extend the `data` argument of `open_run` to allow specifying multiple and arbitrary locations relative to the proposal root. The main use case is the ONC offline corrections, which by default output to `<proposal>/scratch/cal`. With this PR, you could open this like:

```python
run = open_run(proposal=123, run=456, data=['raw', 'scratch/cal'])
```

The previous case `data='all'` is implemented as an alias for `['raw', 'proc']`, and it preserves the overwriting rules we established for it.

### CODE REVIEW

**Comment by philsmt** [comment]
Do you think we're still going for some layer implementation or we can continue here?

**Comment by takluyver** [comment]
I've rebased this onto current master. Now that loading aliases no longer prints a message (#478), I've also simplified the logic a little bit to just load the aliases again for each origin.

@philsmt would you have time to write a test for this?

**Comment by philsmt** [comment]
Thanks, I did! The diff looks weird, but essentially I moved the bits testing `data='all'` from `test_open_run` into `test_open_run_multiple` parametrizing `all` and `['raw', 'proc']`.

**Comment by takluyver** [comment]
Thanks,  LGTM

**Comment by philsmt** [comment]
Thanks for review, probably my MR with the longest review time. Could've waited the two weeks to make it 2 years 😁

**Pull request merged**
