### PR TITLE
Make dependencies for karabo_bridge streaming optional

### PR DESCRIPTION
**Pull request by takluyver**
Including making psutil optional. Part of #210.

- [x] What to call the extra? `bridge`? `stream`? `streaming`?
- [x] Document extra

### CODE REVIEW

**Comment by tmichela** [comment]
What about the cli `karabo-bridge-serve-files`? I guess it will be installed even with the non optional 'bridge' install? that might confuse users 🤔

**Comment by philsmt** [comment]
If I remember correctly, entry points can be made conditional on an extra feature to be installed, but this is apparently not recommended anymore (https://packaging.python.org/specifications/entry-points/). I don't see a proposed alternative

We could just throw an exception if the CLI is called and karabo_bridge is not installed. The idea was that the relative intersection of users using EXtra-data and `karabo-bridge-serve-files` at the same time is smaller than users using `karabo-bridge-serve-files` and `karabo_bridge`.

**Comment by takluyver** [comment]
Maybe that's why we didn't make it optional before. :thinking: 

We could put the files-to-karabo-bridge code in its own tiny package which depends on karabo-bridge and EXtra-data, so neither of them have to depend on the other. I'm a bit reluctant to spin out such small packages, though - my experience is that it's more maintenance work for us and more confusion for users.

**Comment by tmichela** [comment]
I'm also not too excited about packaging something that small...
`karabo_bridge` deps are quite small, maybe that's best to just leave it like that? It's deps are likely to be already present in most environements (numpy, pyzmq, msgpack), with the exception of `msgpack_numpy`, but it itself has no extra dependencies, and we could actually deprecate it by not supporting the format `1.0`. I'm pretty certain that there is no-one using it.

**Comment by takluyver** [comment]
Numpy is a dependency anyway, but psutil, msgpack & pyzmq together (all compiled packages) make for a fairly tempting target. @philsmt noticed users being mildly surprised at how many dependencies EXtra-data & EXtra-geom had - I don't think they were actually complaining, but I thought it might be time to see if we could trim things back a bit.

Would it be reasonable, if `karabo-bridge-serve-files` is used and it can't import what it needs, to exit with a descriptive message?

```
karabo-bridge-serve-files requires additional dependencies:
    pip install karabo-bridge psutil
```

**Comment by tmichela** [comment]
fine with me 👍

**Comment by philsmt** [comment]
This helps a lot, thanks!

**Comment by takluyver** [comment]
Any preference what the extra is called? That's the name you'd need in square brackets for installation, e.g. `pip install extra_data[bridge]` .

**Comment by tmichela** [comment]
either `bridge` or `stream` work for me

**Comment by takluyver** [comment]
OK, let's stick with `bridge` unless @philsmt wants to make a case for some other name. We're already using 'bridge' in the command name and in the client library, so that makes the connection fairly clear.

**Pull request merged**
