### PR TITLE
Try unpinning readthedocs-sphinx-search

### PR DESCRIPTION
**Pull request by takluyver**
See if this fixes the search page (thanks @daniloefl for finding the error)

### CODE REVIEW

**Comment by daniloefl** [comment]
It seems to work, but I noticed that I had to do:
```
sudo apt install pandoc # This does not seem to be available otherwise and pip install was not enough
pip install .[docs]
pip install sphinx_rtd_theme # this is not mentioned in setup.py
cd docs
make html
```

I have now added the theme in the setup.py. I am guessing pandoc is already in the Docker container, otherwise tests would be failing, but it probably has been added as an indirect dependency.

**Comment by takluyver** [comment]
Unfortunately it still doesn't seem to work, at least for me, on RTD itself: https://extra-data--392.org.readthedocs.build/en/392/search.html?q=union&check_keywords=yes&area=default

**Comment by daniloefl** [comment]
Firefox's Javascript log seems to indicate something is missing.
```
Loading failed for the <script> with source “https://extra-data--392.org.readthedocs.build/_/static/javascript/readthedocs-analytics.js”. [search.html:40:1](https://extra-data--392.org.readthedocs.build/en/392/search.html?q=union&check_keywords=yes&area=default)
JQuery not found. Injecting. [readthedocs-doc-embed.js:1:32507](https://extra-data--392.org.readthedocs.build/_/static/javascript/readthedocs-doc-embed.js)
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://media.ethicalads.io/media/client/beta/ethicalads.min.js [readthedocs-doc-embed.js:1:30491](https://extra-data--392.org.readthedocs.build/_/static/javascript/readthedocs-doc-embed.js)
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://readthedocs.org/api/v2/sustainability/data/?callback=jQuery363024195343248548729_1680781230523&format=jsonp&project=extra-data&_=1680781230524 [jquery.js:1:83594](https://extra-data--392.org.readthedocs.build/_/static/vendor/jquery.js)
Error registering page view [readthedocs-doc-embed.js:1:22036](https://extra-data--392.org.readthedocs.build/_/static/javascript/readthedocs-doc-embed.js)
Loading failed for the <script> with source “https://media.ethicalads.io/media/client/beta/ethicalads.min.js”.
```

**Comment by takluyver** [comment]
I think I had the same error before - I upgraded versions of all the packages in #378, and that seemed to fix it at the time. But something must have changed on RTD since then.

**Comment by takluyver** [comment]
Aha: https://github.com/readthedocs/sphinx_rtd_theme/issues/1452

I'll close this one and open a new PR with the workaround suggested there.

**Pull request closed without merging**
