### PR TITLE
Check keys without scanning entire file

### PR DESCRIPTION
**Pull request by takluyver**
Checking for the existence of a single key was scanning all the keys of that source (though it was cached). I thought this would be a relatively small amount of overhead, but a user at MID ran into a case where it seems to be ridiculously slow (familiar story?).

Testing with this script, the `AGIPD1M()` call takes 100s of seconds with master, and <2 seconds with this branch.

```python
from extra_data import RunDirectory
from extra_data.components import AGIPD1M
from time import monotonic

t0 = monotonic()
run = RunDirectory('/gpfs/exfel/exp/MID/202030/p900139/proc/r0036')
t1 = monotonic()
print(f'Opened run in {t1 - t0} s')

agipd = AGIPD1M(run)
t2 = monotonic()
print(f'AGIPD1M() in {t2 - t1} s')
```

### CODE REVIEW

**Comment by tmichela** [comment]
It can probably be even further sped up for control (slow) data with the new file format. the `RUN` group in each files contains a list of all sources and keys for the whole run (replicated in all files).

**Comment by takluyver** [comment]
We'll need to find some way to provide access to the RUN section, but for now I think this should check if a key exists in the CONTROL/INSTRUMENT sections, because that's what we access. CONTROL will be a subset of RUN, if I've understood correctly.

**Comment by tmichela** [comment]
> CONTROL will be a subset of RUN, if I've understood correctly.

yep

**Comment by tmichela** [comment]
LGTM

**Comment by takluyver** [comment]
Thanks :-)

**Pull request merged**
